# Generated by Django 3.2.8 on 2021-10-25 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, null=True)),
                ('alumni_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('alumni_name_abbreviation', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('national_Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('town', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('lga', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique_for_date='date_created')),
                ('confirmed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
